### ISSUE TITLE
Can I use react router dom?

### ISSUE THREAD

**Issue by WildEgor** [wbkd/react-starter#376]
Hi, i have some issues. What will be the usage settings of webpack together with react router dom? Any advice? 
In CRA everything works fine...

**Comment by moklick** [comment]
You don't need to change any webpack options. Do you get an error? What is the issue?

**Comment by WildEgor** [comment]
Yesterday I have got error: 
`(0 , path_to_regexp__WEBPACK_IMPORTED_MODULE_11__.default) is not a function...`

with package.json config: 
`"react-router-dom": "^5.2.0",
"path-to-regexp": "^6.2.0",`

But today switch to "path-to-regexp": "^2.4.0" and everything works.
