### ISSUE TITLE
Eslint complains about Line endings when running app on windows

### ISSUE THREAD

**Issue by geomC** [wbkd/react-starter#5]
Thanks for the boilerplate! I `ve read that contributions are welcome, so I would propose a fix for a propblem I encountered:

When I boot the app using a fresh repo on my Windows 10 system, the terminal is full of those errors:
```
 error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

### Proposal

Add `"linebreak-style": 0` to `.eslintrc`.

### PR?

I would like to do a PR, but I cannot push my feature branch:

```
D:\react-starter>git push origin pr/linebreak-style
remote: Permission to wbkd/react-starter.git denied to geomC.
fatal: unable to access 'https://github.com/wbkd/react-starter/': The requested URL returned error: 403

````

**Comment by muhammadridho** [comment]
hi @geomC  you can fork this repository and create pull request from there .

**Comment by moklick** [comment]
Hey @geomC,

I just added `linebreak-style: 0` to `.eslintrc`. Could you check if it works now?

**Comment by geomC** [comment]
Jup, works like a charm, thanks!
